apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: lcg8b33zt-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/lcg8b33zt-java-quarkus-gitops